spring:
  batch:
    jdbc:
      initialize-schema: always
  application:
    name: ContasBancariasJob
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    springbatch:
      url: jdbc:mysql://localhost:3306/spring_batch?allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: root
      driver: com.mysql.cj.jdbc.Driver
    app:
      url: jdbc:mysql://localhost:3306/app?allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: root
      driver: com.mysql.cj.jdbc.Driver